import storeImage from '../../assets/storeImage.jpeg';
import storeImage1 from '../../assets/WOWMINH.png';

export const storeList = [
  {
    id: 2,
    name: 'Demo Store',
    email: 'demostore@gmail.com',
    phone: '0987654321',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: '09:00:00',
    close_time: '23:00:00',
    rating: 0.0,
    slug: 'demo-store',
    is_valid: false,
    owner: 1,
    store_category: 'tra-sua',
  },
  {
    id: 3,
    name: 'Demo Owner 001',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A, ward B, city C',
    logo: storeImage,
    open_time: '09:00:00',
    close_time: '23:00:00',
    rating: 0.0,
    slug: 'demo-owner-001',
    is_valid: false,
    owner: 3,
    store_category: 'bua-sang',
  },
  {
    id: 4,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage1,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'tra-sua',
  },
  {
    id: 1,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'trai-cay',
  },
  {
    id: 5,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'an-vat',
  },
  {
    id: 6,
    name: 'Demo Store',
    email: 'demostore@gmail.com',
    phone: '0987654321',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: '09:00:00',
    close_time: '23:00:00',
    rating: 0.0,
    slug: 'demo-store',
    is_valid: false,
    owner: 1,
    store_category: 'an-vat',
  },
  {
    id: 7,
    name: 'Demo Owner 001',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A, ward B, city C',
    logo: storeImage,
    open_time: '09:00:00',
    close_time: '23:00:00',
    rating: 0.0,
    slug: 'demo-owner-001',
    is_valid: false,
    owner: 3,
    store_category: 'bua-trua',
  },
  {
    id: 8,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage1,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'tra-sua',
  },
  {
    id: 9,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'tra-sua',
  },
  {
    id: 10,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'tra-sua',
  },
  {
    id: 11,
    name: 'Demo Store',
    email: 'demostore@gmail.com',
    phone: '0987654321',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: '09:00:00',
    close_time: '23:00:00',
    rating: 0.0,
    slug: 'demo-store',
    is_valid: false,
    owner: 1,
    store_category: 'tra-sua',
  },
  {
    id: 12,
    name: 'Demo Owner 001',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A, ward B, city C',
    logo: storeImage,
    open_time: '09:00:00',
    close_time: '23:00:00',
    rating: 0.0,
    slug: 'demo-owner-001',
    is_valid: false,
    owner: 3,
    store_category: 'bua-trua',
  },
  {
    id: 13,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage1,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'tra-sua',
  },
  {
    id: 14,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'tra-sua',
  },
  {
    id: 15,
    name: 'Demo Owner 002',
    email: 'demo_owner_001@gmail.com',
    phone: '0123456789',
    description: null,
    address: '123 street A ward B city C',
    logo: storeImage,
    open_time: null,
    close_time: null,
    rating: 0.0,
    slug: 'demo-owner-002',
    is_valid: false,
    owner: 3,
    store_category: 'bua-sang',
  },
];
